<?xml version="1.0" encoding="utf-8"?><Database Name="Linq_project" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Linq_project;Integrated Security=True;Persist Security Info=True" SettingsObjectName="Linq.DataAccess.Properties.Settings" SettingsPropertyName="Linq_projectConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_createSimpleTable" Method="sp_createSimpleTable">
    <Parameter Name="input" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="json" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>